#!/bin/bash

# go to directory that script is in
PGSF_DIR="$(dirname $0)"
cd "$PGSF_DIR"

# get psql connection string from .pgsf file:
CONNSTR=$(./pg.py)

# get shema name
DB_SCHEMA=$(python3 -c "import config; print(config.DB_SCHEMA)")

TRY=0
while [[ $TRY != 20 ]]
do
	psql -d "$CONNSTR" -c "update \"$DB_SCHEMA\".__sync set status='ready' where status='running'"
	if [[ $? == 0 ]]
	then
		exit 0
	fi
	echo "psql failed. Retying..." >&2
	sleep 3
	TRY=$(( $TRY + 1 ))
done
