#!/bin/bash

# go to directory that script is in
PGSF_DIR="$(dirname $0)"
cd "$PGSF_DIR"

# get psql connection string from .pgsf file:
CONNSTR=$(./pg.py)

# get shema name
DB_SCHEMA=$(python3 -c "import config; print(config.DB_SCHEMA)")

tables=$(psql -d "$CONNSTR" -c "select tablename from \"$DB_SCHEMA\".__sync where status='ready' and last_refresh + refresh_minutes * interval '1 minute' < current_timestamp at time zone 'utc'" --tuples-only)
for table in $tables
do
	#echo "Syncing $table"
	./query_poll_table.py "$table" &
done

wait
